version: "3.9"

services:
    db:
        image: postgres:16.4-alpine3.20
        ports:
            - "5432:5432"
        volumes:
            - ./storages/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
    pgdata:
